apiVersion: v1
kind: Deployment
metadata:
  name: encouragemint-api
  labels:
    name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      encouragemint-component: api
  template:
    metadata:
      labels:
        encouragemint-component: api
    spec:
      containers:
        - name: encouragemint-api
          image: ryan684/encouragemint:latest
          ports:
            - containerPort: 8000