apiVersion: v1
kind: Service
metadata:
  name: encouragemint-api-service
spec:
  selector:
    encouragemint-component: api-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort