apiVersion: v1
kind: Service
metadata:
  name: encouragemint-backend-svc
  labels:
    app: encouragemint-backend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: encouragemint-backend
