SPRING = "SPRING"
SUMMER = "SUMMER"
AUTUMN = "AUTUMN"
WINTER = "WINTER"
EARLY_SPRING = f"EARLY {SPRING}"
LATE_SPRING = f"LATE {SPRING}"
ALL_SPRING = f"ALL {SPRING}"
EARLY_SUMMER = f"EARLY {SUMMER}"
LATE_SUMMER = f"LATE {SUMMER}"
ALL_SUMMER = f"ALL {SUMMER}"
EARLY_AUTUMN = f"EARLY {AUTUMN}"
LATE_AUTUMN = f"LATE {AUTUMN}"
ALL_AUTUMN = f"ALL {AUTUMN}"
EARLY_WINTER = f"EARLY {WINTER}"
LATE_WINTER = f"LATE {WINTER}"
ALL_WINTER = f"ALL {WINTER}"

JANUARY = "jan"
FEBUARY = "feb"
MARCH = "mar"
APRIL = "apr"
MAY = "may"
JUNE = "jun"
JULY = "jul"
AUGUST = "aug"
SEPTEMBER = "sep"
OCTOBER = "oct"
NOVEMBER = "nov"
DECEMBER = "dec"

BLOOM_MONTHS = {
    EARLY_SPRING: f"{MARCH},{APRIL}",
    LATE_SPRING: f"{APRIL},{MAY}",
    ALL_SPRING: f"{MARCH},{APRIL},{MAY}",
    EARLY_SUMMER: f"{JUNE},{JULY},{AUGUST}",
    LATE_SUMMER: f"{JULY},{AUGUST}",
    ALL_SUMMER: f"{JUNE},{JULY},{AUGUST}",
    EARLY_AUTUMN: f"{SEPTEMBER},{OCTOBER}",
    LATE_AUTUMN: f"{OCTOBER},{NOVEMBER}",
    ALL_AUTUMN: f"{SEPTEMBER},{OCTOBER},{NOVEMBER}",
    EARLY_WINTER: f"{DECEMBER},{JANUARY}",
    LATE_WINTER: f"{JANUARY},{FEBUARY}",
    ALL_WINTER: f"{DECEMBER},{JANUARY},{FEBUARY}"
}
