# Generated by Django 2.2.7 on 2019-11-27 12:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('garden_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('garden_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=25)),
                ('duration', models.CharField(max_length=25)),
                ('bloom_period', models.CharField(max_length=25)),
                ('growth_period', models.CharField(max_length=25)),
                ('growth_rate', models.CharField(max_length=25)),
                ('shade_tolerance', models.CharField(max_length=25)),
                ('moisture_use', models.CharField(max_length=25)),
                ('family_name', models.CharField(max_length=25)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encouragemint.Garden')),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encouragemint.Profile'),
        ),
    ]
