# Generated by Django 2.2.7 on 2019-12-28 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden_id', models.UUIDField(default=uuid.uuid4)),
                ('garden_name', models.CharField(max_length=25)),
                ('direction', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.UUIDField(default=uuid.uuid4)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.UUIDField(default=uuid.uuid4)),
                ('common_name', models.CharField(max_length=50)),
                ('trefle_id', models.IntegerField()),
                ('scientific_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=25, null=True)),
                ('bloom_period', models.CharField(max_length=25, null=True)),
                ('growth_period', models.CharField(max_length=25, null=True)),
                ('growth_rate', models.CharField(max_length=25, null=True)),
                ('shade_tolerance', models.CharField(max_length=25, null=True)),
                ('moisture_use', models.CharField(max_length=25, null=True)),
                ('family_common_name', models.CharField(max_length=50)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='encouragemint.Garden')),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to='encouragemint.Profile'),
        ),
    ]
