version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r encouragemint/requirements.txt
            sudo pip install pylint
      - run:
          name: run pylint
          command: pylint encouragemint/*.py --disable=E0401,C0103

      - run:
          name: run tests
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/django
            python encouragemint/manage.py test --settings=encouragemint.settings.local --cover-html --with-xunit --xunit-file=$CIRCLE_TEST_REPORTS/django/test_result.xml --cover-html-dir=$CIRCLE_TEST_REPORTS/django

      - store_artifacts:
          path: encouragemint/test_results
          destination: test

      - store_test_results:
          path: encouragemint/test_results