from backend.tests.unit_tests.test_serializers import *
from backend.tests.unit_tests.test_urls import *
from backend.tests.unit_tests.test_views import *
from backend.tests.unit_tests.test_weather import *
from backend.tests.unit_tests.test_recommender import *
from backend.tests.unit_tests.test_garden_locator import *
from backend.tests.unit_tests.interfaces.trefle.test_trefle import *
from backend.tests.unit_tests.interfaces.meteostat.test_meteostat import *
from backend.tests.integration_tests.test_api_integration import *
