apiVersion: apps/v1
kind: Deployment
metadata:
  name: encouragemint-api
  namespace: default
  labels:
    app.kubernetes.io/name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
      - name: encouragemint-api
        image: ryan684/encouragemint:latest
        command:
          - ./start_web.sh
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: api-port
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: api-port
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: django-secret-key
        - name: TREFLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: trefle-api-key
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: google-api-key
        - name: METEOSTAT_API_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: meteostat-api-key
        - name: WEATHER_DATA_FEATURE_FLAG
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: weather-data-feature-flag
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: django-settings-module
        ports:
          - containerPort: 8000
            name: api-port
      imagePullSecrets:
        - name: docker-hub-credentials