apiVersion: apps/v1
kind: Deployment
metadata:
  name: encouragemint
  namespace: default
  labels:
    app.kubernetes.io/name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
      - name: encouragemint
        image: ryan684/encouragemint:latest
        command:
          - ./start_web.sh
        imagePullPolicy: Always
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: keys
              key: django-secret-key
        - name: TREFLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: keys
              key: trefle-api-key
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: keys
              key: google-api-key
        - name: METEOSTAT_API_KEY
          valueFrom:
            secretKeyRef:
              name: keys
              key: meteostat-api-key
        - name: DJANGO_SETTINGS_MODULE
          value: "backend.settings.production"
        ports:
          - containerPort: 8000
      imagePullSecrets:
        - name: docker-hub-credentials